from setuptools import setup, find_packages

setup(
    name="scMethylSeq",
    version="0.1.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive toolkit for single-cell DNA methylation analysis",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/scMethylSeq",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "scanpy>=1.9.0",
        "anndata>=0.8.0",
        "pybedtools>=0.9.0",
        "pysam>=0.19.0",
        "joblib>=1.1.0",
        "tqdm>=4.62.0",
        "click>=8.0.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "umap-learn>=0.5.0",
        "leidenalg>=0.8.0",
        "igraph>=0.10.0",
        "dask[complete]>=2021.10.0",
        "pyarrow>=6.0.0",
    ],
    entry_points={
        "console_scripts": [
            "scmethyl=scmethylseq.cli:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
